# Generated by Django 2.2.24 on 2021-12-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='published_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
